package review

import (
	"fmt"
	"strings"
	"time"
)

type CreateResponse struct {
	ReviewID     string
	Status       string
	FriendlyName string
}

type Response struct {
	Status  string
	Summary string
}

func IsFakeReviewBuild(mode string) bool {
	return strings.EqualFold(strings.TrimSpace(mode), "fake")
}

func FakeReviewWaitDuration(raw string) (time.Duration, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return 30 * time.Second, nil
	}

	d, err := time.ParseDuration(raw)
	if err != nil {
		return 0, fmt.Errorf("invalid LRC_FAKE_REVIEW_WAIT %q: %w", raw, err)
	}
	if d <= 0 {
		return 0, fmt.Errorf("LRC_FAKE_REVIEW_WAIT must be > 0, got %q", raw)
	}
	return d, nil
}

func BuildFakeSubmitResponse(now time.Time, friendlyName string) CreateResponse {
	ts := now.UnixNano()
	return CreateResponse{
		ReviewID:     fmt.Sprintf("fake-%d", ts),
		Status:       "queued",
		FriendlyName: friendlyName,
	}
}

func BuildFakeCompletedResult() *Response {
	return &Response{
		Status: "completed",
		Summary: `# Fake Review Summary

This is a fake review generated by ` + "`build-local-test`" + ` for end-to-end testing.

- No AI request was sent
- Review data is synthetic and deterministic

## Overview

The connector handler refactor adds empty-payload validation and provider-name normalization. Configuration scaffolding and edge-case fixtures have been updated to extend test coverage.

## Technical Highlights

- ` + "`src/ui_connectors_handlers.go`" + `: ` + "`handleConnector`" + ` now rejects empty payloads and injects a default ` + "`provider`" + ` key, closing a class of silent dispatch failures.
- ` + "`src/fake_large_config.toml`" + `: New config scaffold added; confirm ` + "`enable_telemetry = true`" + ` is intentional before merging to a shared environment.

## Impact

Risk: Enabling telemetry in a generated config file may expose test-run metadata to analytics endpoints — scope this flag to local-only builds before promoting to CI.`,
	}
}
